config/routes.rb
Rails.application.routes.draw do
  resources :users
  root "user_lists#index"

  resources :user_lists
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
end

app/models/user_list.rb
class UserList < ApplicationRecord
  validates :name, presence: true
  validates :phone_number, presence: true, length: { minimum: 11, maximum: 11 },
            numericality: { only_integer: true }

  validate :check_ddd

  def check_ddd
    ddd = phone_number[0..1].to_i
    if ddd < 11 || ddd > 98
      errors.add(:phone_number, "DDD inválido!")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/user_lists_controller.rb
class UserListsController < ApplicationController
  def index
    @user_list = UserList.all
  end

  def show
    @user_list = UserList.find(params[:id])
  end

  def new
    @user_list = UserList.new
  end

  def create
    @user_list = UserList.new(user_lists_params)
    if @user_list.save
      flash[:notice] = "Novo contato criado com sucesso!"
      redirect_to user_lists_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @user_list = UserList.find(params[:id])
  end

  def update
    @user_list = UserList.find(params[:id])
    if @user_list.update(user_lists_params)
      flash[:notice] = "Contato atualizado com sucesso!"
      redirect_to user_lists_path
    else
       render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user_list = UserList.find(params[:id])
    @user_list.destroy
    flash[:notice] = "Contato deletado com sucesso!"

    redirect_to user_lists_path
  end

  private

  def user_lists_params
    params.require(:user_list).permit(:name, :phone_number)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_list_helper.rb
module UserListHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div>
      <%= flash[:notice] %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/user_lists/_form.html.erb
<%= form_with model: user_list do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/user_lists/_user_list.html.erb
<div id="<%= dom_id(user_list) %>">
  <li>
    <%= user_list.name %>
    <%= user_list.phone_number %>
  </li>
    <%= button_to "Delete User list", user_list, method: :delete,
                  form: { data: { turbo_confirm: "Tem certeza?" }} %>
</div>

app/views/user_lists/edit.html.erb
<h1>Edição de contatos</h1>
<%= render "user_lists/form", user_list: @user_list %>

app/views/user_lists/index.html.erb
<h1>Lista de Contato</h1>
<%= render partial: "user_list", collection: @user_list %>
<%# @user_list.each do |each| %>
  <%#= render partial: "user_list", user_list: each %>
<%# end %>
<%= link_to "Novo Contato", new_user_list_path %>

app/views/user_lists/new.html.erb
<h1>Novo Contato</h1>
<%= render "user_lists/form", user_list: @user_list %>

app/views/user_lists/show.html.erb
<h1>Lista de contato</h1>

<p><%= @user_list.name %></p>
<p><%= @user_list.phone_number %></p>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>